### ISSUE TITLE
Uncaught TypeError: this.onTimeout is not a function

### ISSUE THREAD

**Issue by ahghygy** [michaelschwarz/Ajax.NET-Professional#16]
core.ashx:395 Uncaught TypeError: this.onTimeout is not a function
    at AjaxPro.Request.timeout (core.ashx:395)

var r = this.onTimeout(this.duration, this);

this line code return error in core.js in chrom browser.

**Comment by michaelschwarz** [comment]
Hi @ahghygy,

can you please provide more details (i.e. some part of your source code) to reproduce the issue?

Thanks a lot!

**Comment by michaelschwarz** [comment]
Hi @ahghygy, please if you can share some code fragments where you noticed this script error?

**Comment by franciscosamuel** [comment]
I'm not sure this is the same issue, but it seems to be and since the original commenter didn't reply, I will add the information here. If it turns out to be a different problem I can open a new issue.

Using version 22.3.20.1 I'm getting:

Uncaught TypeError: this.onLoading is not a function
    abort http://atlaslocal/Atlas/ajaxpro/core.ashx:308
    timeout http://atlaslocal/Atlas/ajaxpro/core.ashx:396
    setTimeout handler*invoke http://atlaslocal/Atlas/ajaxpro/core.ashx:448
    invoke http://atlaslocal/Atlas/ajaxpro/core.ashx:552
    (my code)::51

I'm not too JS savvy and I don't know if this is intended behavior, but it looks like the problem is that timeouts are being incorrectly triggered. AJAX requests are executed and immediately return but the timeout function is still executed and when it does I get that exception.

**Comment by michaelschwarz** [comment]
Hi @franciscosamuel,

do you have an example code that you are using?

Regards,
Michael

**Comment by franciscosamuel** [comment]
Hi @michaelschwarz 

Here it goes:

[WebApplication1.zip](https://github.com/michaelschwarz/Ajax.NET-Professional/files/8753515/WebApplication1.zip)

**Comment by michaelschwarz** [comment]
Hi @franciscosamuel , I cannot reproduce your issue. However, I prefer not to use the sync call but instead the async one, otherwise your web browser window may freeze in case the execution is running longer.

Please see your example with sync and async calls below:

[WebApplication1-async.zip](https://github.com/michaelschwarz/Ajax.NET-Professional/files/10049635/WebApplication1-async.zip)
[WebApplication1-sync.zip](https://github.com/michaelschwarz/Ajax.NET-Professional/files/10049636/WebApplication1-sync.zip)

**Comment by michaelschwarz** [comment]
Hi @franciscosamuel 

Did you had the chance to review my two examples as I cannot reproduce your issue?

**Comment by franciscosamuel** [comment]
Hi @michaelschwarz I'm sorry for the late response. 
I understand async calls is preferrable and I do use them but i have on very specific use case in which it is preferrable to use the sync version.

You can easily reproduce the problem in your sync sample if you just wait for 30 seconds (or however long the timeout is) after the sync call ends.
